### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by smcgrat** [NWTC/FAST#1]
Hi everyone, I'm trying to follow the instructions at https://github.com/old-NWTC/FAST/blob/master/Compiling/CompilingInstructions.md#NonWindowsCompile but running into a problem. I have the Registry and MAP++ steps done. I did have to edit the make file for how MAP++ links to lapacke but the library was generated so I don't think that is the issue.

The problem I encounter is when doing a `make` in `~/src/FAST/Compiling` leads to the following error:
```
Registry warning: type MeshMapType used before defined for IceD_P_2_SD_P
Registry warning: type MeshMapType used before defined for SD_P_2_IceD_P
generating ../Source/FAST_Types.f90
make: *** [../Source/FAST_Types.f90] Segmentation fault
make: *** Deleting file `../Source/FAST_Types.f90'
```
I've attached the full output from the attempted compilation here.

Here are some environment details:
```
$ gfortran --version
GNU Fortran (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat /etc/redhat-release 
Scientific Linux release 6.10 (Carbon)
$ uname -r
2.6.32-754.3.5.el6.x86_64
```

I'd really appreciate any help you can offer and sorry if I'm missing something basic or obvious.
[FAST_compilation_output.txt](https://github.com/old-NWTC/FAST/files/2652746/FAST_compilation_output.txt)

**Comment by bjonkman** [comment]
It looks like the FAST Registry does not have the correct include paths so it can't find the Registry input files. That, said, the old-NWTC repositories are here for historical reasons and not supported in this form. You can instead get the latest source code and build scripts from the OpenFAST repository: https://github.com/OpenFAST/openfast. It should be easier on non-Windows systems.

**Comment by smcgrat** [comment]
Many thanks. I got OpenFAST to install much more easily. Hopefully it will suit our users needs.
